A bit more info about _vshIoMount/vshIoUmount
vitasdk/vita-headers pull request #837
Opened 2024-08-13 15:00 UTC by v-atamanenko

2024-08-13 16:30 UTC, v-atamanenko commented
@d3m3vilurr can you merge?

2024-08-15 16:33 UTC, v-atamanenko commented
@Princess-of-Sleeping can you merge? :)

2024-08-15 16:39 UTC, Rinnegatamante requested changes

2024-08-15 16:39 UTC, Rinnegatamante commented on include/psp2/vshbridge.h
> + * @param[in] id - Mount ID.
You could add here `(One of ::SceVshMountId)`

2024-08-15 16:39 UTC, Rinnegatamante commented on include/psp2/vshbridge.h
> + * @param[in] id - Mount ID.
same here

2024-08-16 04:11 UTC, merged